
spring:
  servlet:
    multipart:
      max-file-size: 200MB #单个文件上传大小
      max-request-size: 600MB #连续上传文件大小


youku1327:
 file:
  root:
    path: "C:\\mydata\\generator\\version06\\" #存储路径

file:
  savePath: "C:\\mydata\\generator"
  downloadpath: "C:\\mydata\\generator"
  filesuffix: [jpg,png,jpeg,doc,docx,xls,xlsx,txt]