# 配置端口
server:
  port: 8092
spring:
  # Redis数据源
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    #password: zxzxz
    jedis:
      pool:
        max-active: 30    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
