# 配置端口
server:
  port: 8090
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.118:3306/shiro?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  # Redis数据源
  redis:
    host: 192.168.100.118
    port: 6379
    timeout: 5000
    password: zxzxz
    jedis:
      pool:
        max-active: 30    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

# mybatis配置信息
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法
  mapper-locations: classpath:mapper/*.xml # mapper对应的xml位置
logging:
  level:
    com.zxzxz.shiro.mapper: debug #日志级别