spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
    url: jdbc:mysql://192.168.0.105:3306/springboot?useUnicode=true&characterEncoding=utf-8 #数据库地址
    username: root #数据库账号
    password: 123456 # 数据密码
    type: com.alibaba.druid.pool.DruidDataSource # 连接池类型
    druid:
      #初始化连接池的连接数量
      initial-size: 5
      # 最小
      min-idle: 5
      # 最大
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 6000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 6000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 3000
