
server:
  port: 9999

spring:
  boot:
    admin:
      client:
        url: 'http://localhost:9999'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS